### PR TITLE
add simple test models

### PR DESCRIPTION
**Pull request by ymh1003**

### CODE REVIEW

**Review by sree314 — CHANGES_REQUESTED** [review]
Looks good to me as far as complexity is concerned. 

If the code was taken from examples/documentation, please put in a link indicating source.

**Comment by ymh1003** [comment]
I've put the link in models.py and added two more files in jupyter-cadquery which are required in stepreader.py.

**Comment by sree314** [comment]
I add requirements.txt so it will work _without_ `jupyter-cadquery` installed.

Just run `pip install -r requirements.txt` in the virtual environment to get the packages if you still encounter errors.

**Review by sree314 — APPROVED** [review]

**Comment by sree314** [comment]
Tagging @redrn , you should be able to get CI working now?

**Pull request merged**
