### PR TITLE
Cli testing tool

### PR DESCRIPTION
**Pull request by Asai-Yume**
Please add/modify your commands to the tests dictionary after you finish implementing your cli tool.

### CODE REVIEW

**Comment by sree314** [comment]
Not merging this until cli is finished.

**Comment by skriegsman** [comment]
Everything looks good to me! Once we all sign off it can be merged

**Comment by AdiraBlumenthal** [comment]
Good to me

**Comment by redrn** [comment]
The failing still cli_tests should be fixed, but merging is fine by me

**Comment by Asai-Yume** [comment]
Good to merge

**Comment by ymh1003** [comment]
Good to me

**Review by skriegsman — APPROVED** [review]
Passed all tests

**Pull request merged**
