### PR TITLE
ci using pytest and github actions

### PR DESCRIPTION
**Pull request by redrn**
initial draft of invoking pytest on each pull request on main

### CODE REVIEW

**Review by sree314 — CHANGES_REQUESTED** [review]
cadquery will be installed into this environment, which require python >= 3.8 and <= 3.10.

Please change the python version.

**Comment by sree314** [comment]
Also, please install from `requirements.txt` too.

**Comment by redrn** [comment]
Updated as requested. Pytest stills failed; not sure if those errors are expected.

**Comment by sree314** [comment]
Looking at the test details, I think it's just the tests failing for now. I'll merge this for now.

**Review by sree314 — APPROVED** [review]

**Pull request merged**
